name: prest
description: "prEST"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  built_collection: ^5.1.1
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  dartz: ^0.10.1
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  html: ^0.15.6
  image_picker: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  printing: ^5.14.2
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  flutter_widget_from_html: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  freezed: ^3.2.3
  json_serializable: 6.11.2
  riverpod_generator: ^4.0.0+1
  very_good_analysis: ^10.0.0
  intl_utils: ^2.8.14

flutter:
  generate: true # КРИТИЧНО для автоматичного створення файлів перекладу
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carusele/
    - assets/images/developer/
    - assets/images/join/
    - assets/images/design/
    - assets/images/team/
    - .env

# НАЛАШТУВАННЯ ПЕРЕКЛАДАЧА
flutter_intl:
  enabled: true
  class_name: S
  main_locale: pl # Польська за замовчуванням
  arb_dir: lib/l10n
  output_dir: lib/generated